### ISSUE TITLE
Maximum Reuse Scheduling

### ISSUE THREAD

**Issue by caspycat** [V2Xgithub/WiLabV2Xsim#21]
Dear V2XSim Authors,

I have been studying this simulator and its related work for the past year for my own graduate studies. I was studying the MRD algorithm in the paper (by past contributors of this project)

[1] G. Cecchini, A. Bazzi, M. Menarini, B. M. Masini, and A. Zanella, “Maximum Reuse Distance Scheduling for Cellular-V2X Sidelink Mode 3,” in 2018 IEEE Globecom Workshops (GC Wkshps), Dec. 2018, pp. 1–6. doi: [10.1109/GLOCOMW.2018.8644360](https://doi.org/10.1109/GLOCOMW.2018.8644360).

The psuedocode in page 3 shows `|Su| = |S| -1` and `|Fu| = |F| - 1`, to check if all the beacons are used:

![image](https://github.com/V2Xgithub/WiLabV2Xsim/assets/32205524/277dc791-5157-4387-98b4-16002d90d620)

But in the simulator code (https://github.com/V2Xgithub/WiLabV2Xsim/blob/557c68d725aa7d423d00ebc946eb3e55b7234c2d/MatFilesResourceAllocationCV2X/BRreassignmentControlledMaxReuse.m#L46) , it just does what appears to be `|Su| = |S|` (without the -1)

Was there a mistake in the pseudocode in the paper or is there a difference in notation?

**Comment by V2Xgithub** [comment]
Dear Chester,
thank you for your interest on our simulator and for your careful review work.
Quite some time has passed since when we wrote that paper and developed that code, thus I had to go again through the algorithm and could not answer immediately.

Indeed, you are right: the algorithm allocates the last resource when sorting them by nearest distance of use; the last one means |Su| = |S|, like in the code. What written in the paper is very likely a typo, maybe related to an initial plan to use vectors from 0 to N-1.

Sorry for the inconvenience and thanks for the notice.

Best regards

Alessandro Bazzi, Ph.D.
Associate Professor @ DEI, Università di Bologna
Associated with WiLab, CNIT
www.alessandrobazzi.com<http://www.alessandrobazzi.com/>
Phone: +39-051-2093880
________________________________
Da: Chester Koh ***@***.***>
Inviato: martedì 19 settembre 2023 04:48
A: V2Xgithub/WiLabV2Xsim ***@***.***>
Cc: Subscribed ***@***.***>
Oggetto: [V2Xgithub/WiLabV2Xsim] Maximum Reuse Scheduling (Issue #21)


Dear V2XSim Authors,

I have been studying this simulator and its related work for the past year for my own graduate studies. I was studying the MRD algorithm in the paper (by past contributors of this project)

[1] G. Cecchini, A. Bazzi, M. Menarini, B. M. Masini, and A. Zanella, “Maximum Reuse Distance Scheduling for Cellular-V2X Sidelink Mode 3,” in 2018 IEEE Globecom Workshops (GC Wkshps), Dec. 2018, pp. 1–6. doi: 10.1109/GLOCOMW.2018.8644360<https://doi.org/10.1109/GLOCOMW.2018.8644360>.

The psuedocode in page 3 shows |Su| = |S| -1 and |Fu| = |F| - 1, to check if all the beacons are used:

[image]<https://user-images.githubusercontent.com/32205524/268826188-277dc791-5157-4387-98b4-16002d90d620.png>

But in the simulator code (https://github.com/V2Xgithub/WiLabV2Xsim/blob/557c68d725aa7d423d00ebc946eb3e55b7234c2d/MatFilesResourceAllocationCV2X/BRreassignmentControlledMaxReuse.m#L46) , it just does what appears to be |Su| = |S| (without the -1)

Was there a mistake in the pseudocode in the paper or is there a difference in notation?

**Comment by caspycat** [comment]
alright, thank you for the clarification
