### ISSUE TITLE
Consult

### ISSUE THREAD

**Issue by LRayer** [V2Xgithub/WiLabV2Xsim#5]
How the code calls other resource allocation Algorithms. For example，BRreassignmentRandom

**Comment by LRayer** [comment]
Or input something on the command line to call other algorithms

**Comment by wzf-cn** [comment]
You could change the allocation algorithms by setting the parameter "BRAlgorithm" with integer number in the command line or config file. The mapping between the Int num. and the algorithm could be found in "initiateBRAssignmentAlgorithm.m".

Another related file is "mainCV2XttiEnds.m"

**Comment by LRayer** [comment]
Thank you very much. I want to know more about the simulator.  Can I add your WeChat？ My WeChat is 13849925260. 
And my qq is 2530674808.

**Comment by LRayer** [comment]
![image](https://user-images.githubusercontent.com/112415180/190614112-a366d6ad-ebf2-466a-902c-1bacc6b1a96b.png)
![image](https://user-images.githubusercontent.com/112415180/190614194-05d81a7c-8cc3-4e17-9e3a-f82c09109526.png)
There are several mistakes I want to ask you in more detail

**Comment by wzf-cn** [comment]
Some BRAlgorithms were not been updated at the same pace as the main simulator because of lots of reasons, such as we are not focusing on that algorithm at the moment, sorry about that.

Of course, any contribution to improve this simulator is very welcome!

**Comment by VittorioTodisco** [comment]
BRAlgorithm = 101 refers to Random Resource allocation for LTE-V2X and NR-V2X, in that case, the sensing is de-activated as each vehicle chooses a resource randomly for each transmission, regardless of the status of the other resources.

Since the sensing is not active, the parameters regarding the sensing must not be specified or simply inactive.
The error you are getting is due to the measurement of the CBR which cannot be calculated as the sensing is not active.
Therefore the parameter 'CBRactive' must be set to false.

**Comment by LRayer** [comment]
> BRAlgorithm = 101是指LTE-V2X和NR-V2X的随机资源分配，在这种情况下，当每辆车为每个传输随机选择一个资源时，无论其他资源的状态如何，传感都会被停用。
> 
> 由于传感未激活，因此不得指定有关传感的参数或只是不激活。您获得的误差是由于CBR的测量引起的，由于传感未激活，因此无法计算。因此，参数“CBR 活动”必须设置为假。

Thank you for your reply
