### ISSUE TITLE
role of stationManagement.transmittingFusedLTE

### ISSUE THREAD

**Issue by student273** [V2Xgithub/WiLabV2Xsim#8]
I would appreciate if the function of the following could be clarified in the simulator:
In initLastPowerCV2X.m there is a variable called NTx which is the number of vehicles transmitting in the same subframe.
There is also a structure attribute called stationManagement.transmittingFusedLTE. I do not fully under the purpose of this attribute which appears to be a vector.
I initially interpreted this as a vector of the number of transmitting vehicles i.e. if NTx is 3 then transmittingFusedLTE is [1,1,1].
However when debugging I notice NTx is 1 (means only vehicle is transmitting) but yet transmittingFusedLTE is [1,1,1,1].
Can the meaning of the transmittingFusedLTE please be clarified?

**Comment by wzf-cn** [comment]
The variable "transmittingFusedLTE" logs the frequency IDs of the beacon resources used by the transmitters at the same slot, for example, if there are 4 groups of subchannels that could be used to transmit the packet, the possible number in this variable would 1~4.

This variable does not always clean its memory in the new timeslot. That means if there are 4 vehicles transmitted in the 1st slot, this variable would have 4 elements, e.g. [1,1,1,1]; But then if only 1 vehicle transmits in the 2nd slot, only the first element of the variable will be updated, e.g. like in your case. 

This will not lead to a problem because the variable "NTx" (or similar variables) would be used at the same time with this variable, e.g. line 70 and 73 in "initLastPowerCV2X.m":
https://github.com/V2Xgithub/WiLabV2Xsim/blob/4350eb63ac091f8769de44ec3d03ad252146fcff/MainFilesCV2X/initLastPowerCV2X.m#L70
